<h1>Soliant Consulting</h1>
<h2>Apigility for Doctrine</h2>

<form method="get" action="<?= $this->url('soliantconsulting-apigility-admin', array()); ?>">
    Module Name: <input type="text" name="moduleName">

    <input class="btn btn-default" type="submit" value="Create Doctrine API">

</form>

<h3>Apigility resources will be created for these entities</h3>

<ul>
<?php
    foreach ($this->allMetadata as $metadata) {
?>
    <li><?= $this->escapeHtml($metadata->name); ?></li>
<?
    }
?>
</ul>

End