<script>
$(function() {
    $('#toggleCheckboxes').on('click', function(event) {
        $('[name="entityClassName[]"]').prop("checked", $(this).is(':checked'));
    });
});
</script>

<h1>Soliant Consulting</h1>
<h2>Apigility for Doctrine</h2>

<form method="post" action="<?= $this->url('soliantconsulting-apigility-admin-create-resources', array('moduleName' => $this->moduleName)); ?>">

<h3>Route Options</h3>

Route Prefix
<input type="text" name="routePrefix" value="api">

<br>
<br>


Use Entity Namespaces for Route
<input type="checkbox" name="useEntityNamespacesForRoute" value="1">
<br>
<br>
Should entity namespaces be used in route names?  e.g. entity name EtreeDb\Db\Entity\UserMeta would route to
<b>{route prefix} . /etree_db/db/entity/user_meta</b>

If you do not select this option the same route would be <b>{route prefix} . /user_meta</b>

<hr>

<h3>Select Entities</h3>

<table class="table table-striped table-hover">
<tr>
    <th>
        <input type="checkbox" id="toggleCheckboxes">
    </th>
</tr>


<?php
    foreach ($this->allMetadata as $metadata) {
?>
<tr>
    <td>
<input type="checkbox" name="entityClassName[]" value="<?= $this->escapeHtml($metadata->name); ?>">
<?= $this->escapeHtml($metadata->name); ?>
    </td>
</tr>
<?php
    }
?>
</table>

<input class="btn btn-success" type="submit" value="Create Api">

</form>
