<h1>Soliant Consulting</h1>
<h2>Apigility for Doctrine</h2>

<h3>Select entities to Apigility-enable for module <?= $this->escapeHtml($this->moduleName); ?></h3>

<script>
    function toggleCheckboxes(source) {
        checkboxes = document.getElementsByName('entityClassName[]');
        for(var i=0, n=checkboxes.length;i<n;i++) {
            checkboxes[i].checked = source.checked;
        }
    }
</script>

Route Prefix
<input type="text" value="" name="routePrefix">
<br>
Include beginning slash and no trailing slash e.g. <b>/api<b>
<br>
<br>

Use Entity Namespaces for Route
<input type="checkbox" name="useEntityNamespacesForRoute" value="1">
<br>
Should entity namespaces be used in route names?  e.g. entity name EtreeDb\Entity\UserMeta would route to
{route prefix} . <b>/etree_db/entity/user_meta<b>
<b>
If you do not select this option the same route would be {route prefix} . <b>/user_meta</b>
<br>
<br>

<input type="checkbox" name="toggleCheckboxes" value="" onClick="toggleCheckboxes(this);">
<br>

<form method="post" action="<?= $this->url('soliantconsulting-apigility-admin-create-resources', array('moduleName' => $this->moduleName)); ?>">

<?php
    foreach ($this->allMetadata as $metadata) {
?>

<input type="checkbox" name="entityClassName[]" value="<?= $this->escapeHtml($metadata->name); ?>">
<?= $this->escapeHtml($metadata->name); ?>
<br>

<?
    }
?>
<br>
<input class="btn btn-success" type="submit" value="Create Api">
</form>
