<script>
$(function() {
    $('#toggleCheckboxes').on('click', function(event) {
        $('[name="entityClassName[]"]').prop("checked", $(this).is(':checked'));
    });

    $('#loadObjectManager').on('click', function(event) {
        window.location = '<?= $this->url('soliantconsulting-apigility-admin-select-entities', array('moduleName' => $this->moduleName)); ?>'
            + '/' + $('#objectManagerAlias').first().val();
        return false;
    });
});
</script>

<?php

use Zend\Form\Form;
use Zend\Form\Element;

$form = new Form('select-entities');
$form->setAttributes(array(
    'action' => $this->url('soliantconsulting-apigility-admin-create-resources', array('moduleName' => $this->moduleName)),
    'method' => 'post',
    'class' => 'form-horizontal'
));

$objectManagerAlias = new Element('objectManagerAlias');
$objectManagerAlias->setAttributes(array(
    'type' => 'text',
    'size' => 80,
    'id' => 'objectManagerAlias',
));
$objectManagerAlias->setLabel('Object Manager Alias');
$objectManagerAlias->setValue(($this->objectManagerAlias) ?: 'doctrine.entitymanager.orm_default');

$doctrineHydrator = new Element('doctrineHydrator');
$doctrineHydrator->setAttributes(array(
    'type' => 'text',
    'size' => 80,
));
$doctrineHydrator->setLabel('Doctrine Hydrator (ODM Only)');
$doctrineHydrator->setValue('DoctrineMongoODMModule\Hydrator\TenantEntityAssetHydrator');

$routePrefix = new Element('routePrefix');
$routePrefix->setAttributes(array(
    'type' => 'text'
));
$routePrefix->setLabel('Route Prefix');
$routePrefix->setValue('api');

$useEntityNamespacesForRoute = new Element\Checkbox('useEntityNamespacesForRoute');
$useEntityNamespacesForRoute->setAttributes(array(
    'type' => 'checkbox',
    'description' => 'Should entity namespaces be used in route names?',
));
$useEntityNamespacesForRoute->setCheckedValue(1);
$useEntityNamespacesForRoute->setUncheckedValue(false);
$useEntityNamespacesForRoute->setLabel('Use Entity Namespaces for Route?');

$form->add($objectManagerAlias);
$form->add($doctrineHydrator);
$form->add($routePrefix);
$form->add($useEntityNamespacesForRoute);
?>

<div class="lead">

<?= $this->form()->openTag($form); ?>
<fieldset>
<legend>Apigility for Doctrine</legend>

<?= $this->formRow($form->get('objectManagerAlias')); ?>

<?php
if ($this->invalidObjectManager) {
?>
<p style="color: red">Invalid Object Manager Alias</p>
<?php
}
?>
<br>
<button id="loadObjectManager" class="btn btn-default">
    Refresh Entity List
</button>
<br>
<?php
if (!$this->invalidObjectManager) {
?>

<?= $this->formRow($form->get('doctrineHydrator')); ?>
<br>
<?= $this->formRow($form->get('routePrefix')); ?>
<br>
<?= $this->formRow($form->get('useEntityNamespacesForRoute')); ?>

</div>

<legend >Select Entities</legend>

<table class="table table-striped table-hover">
<tr>
    <th>
        <input type="checkbox" id="toggleCheckboxes">
    </th>
</tr>


<?php
    foreach ($this->allMetadata as $metadata) {
?>
<tr>
    <td>
<input type="checkbox" name="entityClassName[]" value="<?= $this->escapeHtml($metadata->name); ?>">
<?= $this->escapeHtml($metadata->name); ?>
    </td>
</tr>
<?php
    }
?>
</table>

<input class="btn btn-success" type="submit" value="Create Api">

<?php
}
?>
</fieldset>
</form>
